# Config file for go-test-coverage github action.

profile: coverage.out
threshold:
  #file: 100
  #package: 80
  total: 75
exclude:
  paths:
    - main\.go$
git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
## name of branch where badges are stored ideally this should be orphan branch
git-branch: .badges
