# Example configuration file for Sargantana Go
# This file demonstrates how to configure the server and various controllers

server:
  # Server address to listen on (required)
  address: "localhost:8080"

  # Session configuration (required)
  session_name: "sargantana-go"
  session_secret: "${SESSION_SECRET}"  # Can use environment variables

  # Optional: Directory containing secret files (for Docker secrets)
  secrets_dir: "/run/secrets"

  # Optional: Redis session store configuration
  # If not provided, cookie-based sessions will be used
  redis_session_store:
    address: "localhost:6379"
    database: 0
    # Optional TLS configuration
    # tls:
    #   cert_file: "/path/to/cert.pem"
    #   key_file: "/path/to/key.pem"
    #   ca_file: "/path/to/ca.pem"

# Optional: Vault configuration for secret management
vault:
  address: "https://vault.example.com:8200"
  token: "${VAULT_TOKEN}"
  path: "secret/data/myapp"
  namespace: ""  # Optional, for Vault Enterprise

# Controllers configuration
controllers:
  # Static file controller
  - type: "static"
    name: "static-files"
    config:
      statics_dir: "./frontend"
      templates_dir: "./templates"

  # Authentication controller
  - type: "auth"
    name: "authentication"
    config:
      # Optional: Custom callback URL (if running behind a proxy)
      # callback_url: "https://myapp.example.com"

      # Authentication paths (optional, these are defaults)
      callback_path: "/auth/{provider}/callback"
      login_path: "/auth/{provider}"
      logout_path: "/auth/logout"
      user_info_path: "/auth/user"
      redirect_on_login: "/"
      redirect_on_logout: "/"

      # OAuth providers configuration
      providers:
        github:
          key: "${GITHUB_KEY}"
          secret: "${GITHUB_SECRET}"
          scopes:
            - "read:user"
            - "user:email"

        google:
          key: "${GOOGLE_KEY}"
          secret: "${GOOGLE_SECRET}"

        # Auth0 example (requires domain)
        auth0:
          key: "${AUTH0_KEY}"
          secret: "${AUTH0_SECRET}"
          domain: "yourdomain.auth0.com"

        # Okta example (requires org_url)
        okta:
          key: "${OKTA_KEY}"
          secret: "${OKTA_SECRET}"
          org_url: "https://yourorg.okta.com"

        # Nextcloud example (requires url)
        nextcloud:
          key: "${NEXTCLOUD_KEY}"
          secret: "${NEXTCLOUD_SECRET}"
          url: "https://nextcloud.example.com"

        # WeCom example (requires corp_id and agent_id)
        wecom:
          key: "${WECOM_KEY}"
          secret: "${WECOM_SECRET}"
          corp_id: "${WECOM_CORP_ID}"
          agent_id: "${WECOM_AGENT_ID}"

  # Load balancer controller
  - type: "load_balancer"
    name: "api-proxy"
    config:
      path: "/api"
      require_auth: true
      endpoints:
        - "http://api1:8080"
        - "http://api2:8080"
        - "http://api3:8080"
